export const dataFields = [
    "Status",
    "Candidate",
    "Client",
    "Offered Position",
    "Date Of Joining",
    "Candidate Owner",
    "Account Manager",
    "Account Head",
    "P&L Head",
    "Resume Source",
    "Billable Salary",
    "Commercial",
    "Fee",
    "Send Off",
    "Security Period",
    "Payment Status",
    "Update",
  ];
 export const fields = [
    "status",
    "candidate",
    "client",
    "offeredPosition",
    "dateOfJoining",
    "cnadidateOwner",
    "accountManager",
    "accountHead",
    "pandLhead",
    "resumeSource",
    "billableSalary",
    "commercial",
    "fee",
    "sendOff",
    "securityPeriod",
    "paymentStaus",
  ];
  export const securityPeriodOptions = ["On-Going", "Completed", "Send-Off"]; // Replace with your actual options
  export const paymentStatusOptions = ["Pending", "Received", "Adjusted", "Returning", "Compromised"]; // Replace with your actual options
